version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
    pihole:
        restart: always
        image: pihole/pihole:latest
        hostname: pihole
        networks:
            lan:
                ipv4_address: 192.168.1.252
        environment:
            TZ: 'Europe/Vienna'
            WEBPASSWORD: ''
        # Volumes store your data between container upgrades
        volumes:
            - ./pihole/pihole/:/etc/pihole/
            - ./pihole/dnsmasq.d/:/etc/dnsmasq.d/
        #tmpfs:
        #    - /etc/pihole/
        #    - /etc/dnsmasq.d/
        #    - /run/pihole/
        #    - /tmp/

networks:
    lan:
        external: true
        name: network_lan
