version: "3.8"
services:
    squid:
        restart: always
        build: ./squid
        networks:
            lan:
                ipv4_address: 192.168.1.253
        cap_add:
            - NET_ADMIN
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
            - ./squid/debian.conf:/etc/squid/conf.d/debian.conf:ro
            - ./squid/squid.conf:/usr/local/squid/etc/squid.conf:ro

networks:
    lan:
        external: true
        name: network_lan
